//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace commitFive
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class commit_fiveEntities : DbContext
    {
        public commit_fiveEntities()
            : base("name=commit_fiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<campusReference> campusReference { get; set; }
        public virtual DbSet<college> college { get; set; }
        public virtual DbSet<noner> noner { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<student> student { get; set; }
    }
}
